name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  # schedule:
  #   # Run every 15 minutes of every hour, starting at 5 minutes (5m, 20m, 35m, 50m).
  #   # The slight offset is there to try and avoid the high load times.
  #   - cron: '5/15 * * * *'

# Make sure jobs cannot overlap (e.g. one from push and one from schedule).
concurrency:
  group: pages-ci
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build the static content using yarn
      run: yarn run build

    - name: Fetch pull request data (julia)
      run: yarn run compose-db
      env:
        GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
        name: web-static
        path: |
          logs/
          out/

    - name: Deploy to GitHub Pages 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: out
        # Configure the commit author.
        git-config-name: 'JuliaLang Organization'
        git-config-email: '<>'
        # Don't keep the history.
        single-commit: true
