name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run every hour, starting at XX:07:00
    - cron: '7 * * * *'

permissions:
  contents: write

concurrency:
  group: pages-ci
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build the static content using yarn
      run: yarn run build

    - name: Fetch pull request data (julia)
      run: yarn run compose-db
      env:
        GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
        name: web-static
        path: |
          logs/
          out/

    - name: Deploy to GitHub Pages 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: out
        # Configure the commit author.
        git-config-name: 'JuliaLang Organization'
        git-config-email: '<>'
        # Don't keep the history.
        single-commit: true
